models/RepairType.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "repair_type".
 *
 * @property int $REPAIR_TYPE_ID
 * @property string $REPAIR_TYPE_NAME
 */
class RepairType extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'repair_type';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['REPAIR_TYPE_ID'], 'required'],
            [['REPAIR_TYPE_ID'], 'integer'],
            [['REPAIR_TYPE_NAME'], 'string', 'max' => 255],
            [['REPAIR_TYPE_ID'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'REPAIR_TYPE_ID' => 'Repair  Type  ID',
            'REPAIR_TYPE_NAME' => 'ประเภทการซ่อม',
        ];
    }
}

models/Repairs.php
<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "repairs".
 *
 * @property string $REPAIR_ID
 * @property string $ITEM_ID
 * @property string $REQUIRE_DATE
 * @property string $PROBLEM_CUASE
 * @property string $REPAIR_DATE
 * @property string $FINISH_DATE
 * @property string $REPAIR_RESULT
 * @property string $REPAIR_NAME
 * @property int $REPAIR_TYPE_ID
 * @property int $REPAIR_DISCHART_ID
 * @property int $SIGN_ID
 * @property string $REPAIR_MONITOR
 * @property Items $iTEM
 * @property RepairDischart $rEPAIRDISCHART
 * @property RepairType $rEPAIRTYPE
 */
class Repairs extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'repairs';
    }

    public $upload_folder ='uploads';

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['ITEM_ID', 'REQUIRE_DATE'], 'required'],
            [['ITEM_ID', 'REPAIR_TYPE_ID', 'REPAIR_DISCHART_ID', 'CHECK_BY_ID','REPAIR_STATUS_ID','SIGN_ID'], 'integer'],
            [['REQUIRE_DATE', 'REPAIR_DATE','REQUIRE_NAME', 'FINISH_DATE','QUARANTINE_DATE'], 'safe'],
            [['PROBLEM_CUASE', 'REPAIR_RESULT','REQUIRE_NAME','PICTURE','COMMENT','REPAIR_MONITOR'], 'string'],
            [['ITEM_ID'], 'exist', 'skipOnError' => true, 'targetClass' => Items::className(), 'targetAttribute' => ['ITEM_ID' => 'ITEM_ID']],
            [['REPAIR_DISCHART_ID'], 'exist', 'skipOnError' => true, 'targetClass' => RepairDischart::className(), 'targetAttribute' => ['REPAIR_DISCHART_ID' => 'REPAIR_DISCHART_ID']],
            [['REPAIR_TYPE_ID'], 'exist', 'skipOnError' => true, 'targetClass' => RepairType::className(), 'targetAttribute' => ['REPAIR_TYPE_ID' => 'REPAIR_TYPE_ID']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'REPAIR_ID' => 'Repair  ID',
            'ITEM_ID' => 'รหัสอุปกรณ์',
            'REQUIRE_DATE' => 'วันที่แจ้งซ่อม',
            'PROBLEM_CUASE' => 'ปัญหาที่พบ',
            'REPAIR_DATE' => 'วันที่ซ่อม',
            'FINISH_DATE' => 'วันที่ซ่อมเสร็จ',
            'QUARANTINE_DATE' => 'วันที่คาดว่าซ่อมเสร็จ',
            'REPAIR_RESULT' => 'ผลการซ่อม',
            'REPAIR_TYPE_ID' => 'ประเภทการซ่อม',
            'REPAIR_STATUS_ID' => 'สถานะการซ่อม',
            'REPAIR_DISCHART_ID' => 'การจำหน่าย',
            'REQUIRE_NAME' => 'ผู้แจ้ง',
            'CHECK_BY_ID' => 'ผู้ซ่อม',
            'PICTURE' => 'รูปประกอบ',
            'REPAIR_MONITOR' => 'สำหรับงานพัสดุ',
            'COMMENT' => 'หมายเหตุ',
            'SIGN_ID' => 'ผู้ลงนาม',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItem()
    {
        return $this->hasOne(Items::className(), ['ITEM_ID' => 'ITEM_ID']);
    }
    
    public function getItemNo(){
        $model=$this->item;
        return $model?$model->ITEM_NO:'';
    }

    public function getItemName(){
        $model=$this->item;
        return $model?$model->ITEM_NAME:'';
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDischart()
    {
        return $this->hasOne(RepairDischart::className(), ['REPAIR_DISCHART_ID' => 'REPAIR_DISCHART_ID']);
    }

    public function getDischartName(){
        $model=$this->dischart;
        return $model?$model->REPAIR_DISCHART_NAME:'';
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRepairtype()
    {
        return $this->hasOne(RepairType::className(), ['REPAIR_TYPE_ID' => 'REPAIR_TYPE_ID']);
    }

    public function getRepairtypeName(){
        $model=$this->repairtype;
        return $model?$model->REPAIR_TYPE_NAME:'';
    }

    public function getRepairby()
    {
        return $this->hasOne(CheckBy::className(), ['CHECK_BY_ID' => 'CHECK_BY_ID']);
    }

    public function getRepairByName(){
        $model=$this->repairby;
        return $model?$model->CHECK_BY_NAME:'';
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRepairstatus()
    {
        return $this->hasOne(RepairStatus::className(), ['REPAIR_STATUS_ID' => 'REPAIR_STATUS_ID']);
    }

    public function getRepairstatusName(){
        $model=$this->repairstatus;
        return $model?$model->REPAIR_STATUS_NAME:'';
    }

    
    public function upload($model,$attribute)
    {
        $photo  = UploadedFile::getInstance($model, $attribute);
        $path = $this->getUploadPath();
        if ($this->validate() && $photo !== null) {

            $fileName = md5($photo->baseName.time()) . '.' . $photo->extension;
        //$fileName = $photo->baseName . '.' . $photo->extension;
            if($photo->saveAs($path.$fileName)){
            return $fileName;
        } else { 
            return null;
        }
        
        }
        return $model->isNewRecord ? false : $model->getOldAttribute($attribute);
    }

    public function getUploadPath(){
        return Yii::getAlias('@webroot').'/'.$this->upload_folder.'/';
    }

    public function getUploadUrl(){
        return Yii::getAlias('@web').'/'.$this->upload_folder.'/';
    }

    public function getPhotoViewer(){
        return empty($this->PICTURE) ? Yii::getAlias('@web').'/img/none.png' : $this->getUploadUrl().$this->PICTURE;
    }
}

controllers/RepairsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Repairs;
use app\models\RepairsSearch;
use app\models\Sign;
use app\models\SignSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\mpdf\Pdf;
use yii\filters\AccessControl;

/**
 * RepairsController implements the CRUD actions for repairs model.
 */
class RepairsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['update','delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all repairs models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RepairsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single repairs model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new repairs model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $model = new Repairs();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->REPAIR_ID]);
        }

        return $this->render('create', [
            'model' => $model,'item_id' => $id 
        ]);
    }

    /**
     * Updates an existing repairs model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->REPAIR_ID]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionPatsdu($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->REPAIR_ID]);
        }

        return $this->render('patsdu', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing repairs model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['admin']);
    }

    /**
     * Lists all repairs models.
     * @return mixed
     */
    public function actionAdmin()
    {
        $searchModel = new RepairsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('admin', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all repairs models.
     * @return mixed
     */
    public function actionPdf($id)
    {
        $model = $this->findModel($id);
        $data = Sign::findOne(['ID'=>1]);

        $content = $this->renderPartial('_preview', [
            'model' => $model,
            'data' => $data,
        ]);

        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8,
            // A4 paper format
            'format' => Pdf::FORMAT_A4,
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT,
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER,
            // your html content input
            'content' => $content,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting
            'cssFile' => '@app/web/css/pdf.css',
            // any css to be embedded if required
            'cssInline' => '.bd{border:1.5px solid; text-align: center;} .ar{text-align:right} .imgbd{border:1px solid}',
            // set mPDF properties on the fly
            'options' => ['title' => 'ตัวอย่างใบส่งซ่อม : '.$id],
            // call mPDF methods on the fly
            'methods' => [
                //'SetHeader'=>[''],
                //'SetFooter'=>['{PAGENO}'],
            ]
        ]);

            // return the pdf output as per the destination setting
        return $pdf->render(); 
    }

    /**
     * Finds the repairs model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return repairs the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = repairs::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/repairs/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\date\DatePicker;
use app\models\RepairType;
use app\models\RepairDischart;
use app\models\CheckBy;
use kartik\icons\Icon;

$repairby = ArrayHelper::map(CheckBy::find()->all(), 'CHECK_BY_ID', 'CHECK_BY_ID');
$repairtype = ArrayHelper::map(RepairType::find()->all(), 'REPAIR_TYPE_ID', 'REPAIR_TYPE_NAME');
$dctype = ArrayHelper::map(RepairDischart::find()->all(), 'REPAIR_DISCHART_ID', 'REPAIR_DISCHART_NAME');

/* @var $this yii\web\View */
/* @var $model app\models\repairs */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="repairs-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="card card-info text-center col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2">
        <?= $form->field($model, 'ITEM_ID')->hiddenInput(['value' => $item_id, 'maxlength' => true])->label(false) ?>

        <?= $form->field($model, 'REQUIRE_DATE')->widget(
            DatePicker::ClassName(),
            [
                'name' => 'REQUIRE_DATE',
                'type' => DatePicker::TYPE_COMPONENT_APPEND,
                'options' => ['placeholder' => 'ระบุวันที่แจ้งซ่อม'],
                'pluginOptions' => [
                    'format' => 'yyyy-mm-dd',
                    'todayHighlight' => true
                ]
            ]
        ); ?>

        <?= $form->field($model, 'PICTURE')->fileInput() ?>

        <?= $form->field($model, 'PROBLEM_CUASE')->textarea(['rows' => 6]) ?>

        <?= $form->field($model, 'REQUIRE_NAME')->textInput(['maxlength' => true]) ?>
        <br>
        <div class="form-group">
            <?= Html::submitButton(Icon::show('save') . ' บันทึก', ['class' => 'btn btn-success btn-block']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/repairs/_form_patsdu.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\RepairType;
use app\models\RepairDischart;
use app\models\CheckBy;
use kartik\icons\Icon;

$repairby = ArrayHelper::map(CheckBy::find()->all(), 'CHECK_BY_ID', 'CHECK_BY_ID');
$repairtype = ArrayHelper::map(RepairType::find()->all(), 'REPAIR_TYPE_ID', 'REPAIR_TYPE_NAME');
$dctype = ArrayHelper::map(RepairDischart::find()->all(), 'REPAIR_DISCHART_ID', 'REPAIR_DISCHART_NAME');

/* @var $this yii\web\View */
/* @var $model app\models\repairs */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="repairs-form">

    <div class="card card-info text-center col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2">
        <b>วันที่</b> <?= $model->REQUIRE_DATE ?><br>
        <b>ปัญหา</b> <?= $model->PROBLEM_CUASE ?><br>
        <b>ผู้แจ้ง</b> <?= $model->REQUIRE_NAME ?><br>
    </div>
    <?php $form = ActiveForm::begin(); ?>

    <div class="card card-info text-center col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2">

        <?= $form->field($model, 'REPAIR_MONITOR')->textarea(['rows' => 3]) ?>

        <?= $form->field($model, 'COMMENT')->textarea(['rows' => 3]) ?>
        <br>
        <div class="form-group">
            <?= Html::submitButton(Icon::show('save') . ' บันทึก', ['class' => 'btn btn-success btn-block']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/repairs/_formupdate.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\date\DatePicker;
use app\models\RepairType;
use app\models\RepairDischart;
use app\models\CheckBy;
use app\models\RepairStatus;
use kartik\icons\Icon;

$repairby = ArrayHelper::map(CheckBy::find()->all(), 'CHECK_BY_ID', 'CHECK_BY_NAME');
$repairtype = ArrayHelper::map(RepairType::find()->all(), 'REPAIR_TYPE_ID', 'REPAIR_TYPE_NAME');
$dctype = ArrayHelper::map(RepairDischart::find()->all(), 'REPAIR_DISCHART_ID', 'REPAIR_DISCHART_NAME');
$repairstatus = ArrayHelper::map(RepairStatus::find()->all(), 'REPAIR_STATUS_ID', 'REPAIR_STATUS_NAME');

/* @var $this yii\web\View */
/* @var $model app\models\repairs */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="repairs-form">
    <div class="card card-info text-center col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2">
        <b>วันที่</b> <?= $model->REQUIRE_DATE ?><br>
        <b>ปัญหา</b> <?= $model->PROBLEM_CUASE ?><br>
        <?= $model->PICTURE ? Html::img($model->photoViewer, ['class' => 'img-thumbnail', 'style' => 'width:300px;']) : Html::img(Yii::getAlias('@web') . '/images/no-image-found.png', ['class' => 'img-thumbnail', 'style' => 'width:300px;']) ?><br>
        <b>ผู้แจ้ง</b> <?= $model->REQUIRE_NAME ?><br>
    </div>
    <?php $form = ActiveForm::begin(); ?>
    <div class="card card-info text-center col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2">

        <?= $form->field($model, 'ITEM_ID')->hiddenInput(['maxlength' => true])->label(false) ?>

        <?= $form->field($model, 'REPAIR_DATE')->widget(
            DatePicker::ClassName(),
            [
                'name' => 'REPAIR_DATE',
                'type' => DatePicker::TYPE_COMPONENT_APPEND,
                'options' => ['placeholder' => 'ระบุวันที่ดำเนินการ'],
                'pluginOptions' => [
                    'format' => 'yyyy-mm-dd',
                    'todayHighlight' => true
                ]
            ]
        ); ?>

        <?= $form->field($model, 'QUARANTINE_DATE')->widget(
            DatePicker::ClassName(),
            [
                'name' => 'QUARANTINE_DATE',
                'type' => DatePicker::TYPE_COMPONENT_APPEND,
                'options' => ['placeholder' => 'ระบุวันที่คาดว่าจะเสร็จ'],
                'pluginOptions' => [
                    'format' => 'yyyy-mm-dd',
                    'todayHighlight' => true
                ]
            ]
        ); ?>

        <?= $form->field($model, 'FINISH_DATE')->widget(
            DatePicker::ClassName(),
            [
                'name' => 'FINISH_DATE',
                'type' => DatePicker::TYPE_COMPONENT_APPEND,
                'options' => ['placeholder' => 'ระบุวันที่เสร็จงาน'],
                'pluginOptions' => [
                    'format' => 'yyyy-mm-dd',
                    'todayHighlight' => true
                ]
            ]
        ); ?>

        <?= $form->field($model, 'REPAIR_RESULT')->textarea(['rows' => 6]) ?>

        <?= $form->field($model, 'REPAIR_TYPE_ID')->dropDownList($repairtype, ['prompt' => 'เลือกประเภทการซ่อม']) ?>

        <?= $form->field($model, 'REPAIR_STATUS_ID')->dropDownList($repairstatus, ['prompt' => 'เลือกสถานะการซ่อม']) ?>

        <?= $form->field($model, 'REPAIR_DISCHART_ID')->dropDownList($dctype, ['prompt' => 'เลือกการจำหน่าย']) ?>

        <?= $form->field($model, 'CHECK_BY_ID')->dropDownList($repairby, ['prompt' => 'เลือกผู้ซ่อม']) ?>

        <br>
        <div class="form-group">
            <?= Html::submitButton(Icon::show('save') . ' บันทึก', ['class' => 'btn btn-success btn-block']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/repairs/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\repairsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="repairs-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>
        <div class="row">
            <div class="col-lg-3">
            </div>
            <div class="col-lg-3">
            </div>
            <div class="col-lg-3">
            </div>
            <div class="col-lg-3">
            </div>
        </div>

    <?= $form->field($model, 'REPAIR_ID') ?>

    <?= $form->field($model, 'ITEM_ID') ?>

    <?= $form->field($model, 'REQUIRE_DATE') ?>

    <?= $form->field($model, 'PROBLEM_CUASE') ?>

    <?= $form->field($model, 'REPAIR_DATE') ?>

    <?php // echo $form->field($model, 'FINISH_DATE') ?>

    <?php // echo $form->field($model, 'REPAIR_RESULT') ?>

    <?php // echo $form->field($model, 'REPAIR_TYPE_ID') ?>

    <?php // echo $form->field($model, 'REPAIR_DISCHART_ID') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/repairs/admin.php
<?php

use kartik\grid\GridView;
use kartik\icons\Icon;
use yii\helpers\Html;
/* @var $this yii\web\View */
/* @var $searchModel app\models\repairsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'รายการซ่อม';
?>
<div class="repairs-index">

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'panel' => [
            'heading' => "ทะเบียนการซ่อม พัสดุ-ครุภัณฑ์ ",
            'type' => GridView::TYPE_PRIMARY
        ],
        'rowOptions' => function ($model) {
            
            if (!$model->REPAIR_DISCHART_ID) {
                return ['style' => 'background-color:#EF9F9F;'];
            }
            else {
                return ['style' => 'background-color:#BDF2D5;'];
            }
        },
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'REPAIR_ID',
            //'ITEM_ID',
            [
                'attribute'=>'ITEM_ID',
                'label'=>'เลขที่อุปกรณ์',
                'format'=>'text',//raw, html
                'content'=>function($data){
                    return $data->getItemNo();
                }
            ],
            [
                'attribute'=>'ITEM_ID',
                'label'=>'ชื่ออุปกรณ์',
                'format'=>'text',//raw, html
                'content'=>function($data){
                    return $data->getItemName();
                }
            ],
            'REQUIRE_DATE',
            'QUARANTINE_DATE',
            'PROBLEM_CUASE:ntext',
//            'REQUIRE_NAME',
            [
                'attribute'=>'REPAIR_STATUS_ID',
                'label'=>'สถานะอุปกรณ์',
                'format'=>'text',//raw, html
                'content'=>function($data){
                    return $data->getRepairStatusName();
                }
            ],
            'REPAIR_RESULT:ntext',
            [
                'attribute'=>'REPAIR_MONITOR',
                'label'=>'พัสดุ',
                'format'=>'text',//raw, html
                'content'=>function($data){
                    return $data->REPAIR_MONITOR;
                }
            ],
            [
                'attribute'=>'REPAIR_DISCHART_ID',
                'label'=>'ผลการจำหน่าย',
                'format'=>'text',//raw, html
                'content'=>function($data){
                    return $data->getDischartName();
                }
            ],
            'FINISH_DATE',
            //'REPAIR_TYPE_ID',
            //'REPAIR_DISCHART_ID',

            [
                'class' => 'yii\grid\ActionColumn',
                'header' => '',
                'options' => ['style' => 'width:160px;'],
                'buttonOptions' => ['class' => 'btn btn-warning btn-sm'],
                'template' => '{print} {pastdu} {update}',
                'buttons' => [
                    'update' => function ($url, $model, $key) {
                        return Yii::$app->user->identity->role == 1 ? Html::a(Icon::show('edit'), ['update', 'id' => $model->REPAIR_ID], ['class' => 'btn btn-warning',]):'';
                    },
                    'pastdu' => function ($url, $model, $key) {
                        return in_array(Yii::$app->user->identity->role,[3,1]) ? Html::a(Icon::show('box'), ['patsdu', 'id' => $model->REPAIR_ID], ['class' => 'btn btn-success']):'';
                    },
                    'print' => function ($url, $model, $key) {
                        return Html::a(Icon::show('print'), ['pdf', 'id' => $model->REPAIR_ID], ['class' => 'btn btn-info', 'linkOptions' => ['target' => '_blank']]);
                    }
                ]
            ],
        ],
    ]); ?>
</div>

views/repairs/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\repairs */

$this->title = 'เพิ่มรายการซ่อม';

?>
<div class="repairs-create">

    <?= $this->render('_form', [
        'model' => $model,'item_id' => $item_id
    ]) ?>

</div>

views/repairs/patsdu.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\repairs */

$this->title = 'พัสดุบันทึก';

?>
<div class="repairs-patsdu">

    <?= $this->render('_form_patsdu', [
        'model' => $model,'item_id' => $item_id
    ]) ?>

</div>